# counter, default (10s)
- match: "{metric_type='counter',metric_interval='default'}"
  interval: 60s
  staleness_interval: 180s
  without: [instance, metric_type, metric_interval]
  outputs: ["total", "sum_samples", "increase", "max"]
  output_relabel_configs:
    - source_labels: [ __name__ ]
      target_label: __name__
      regex: "(.+):.+_(.+)"
      replacement: "$1:$2"

# gauge, default (10s)
- match: "{metric_type='gauge',metric_interval='default'}"
  interval: 30s
  staleness_interval: 120s
  without: [instance, metric_type, metric_interval]
  outputs: ["histogram_bucket", "quantiles(0.50, 0.99)"]
  output_relabel_configs:
    - source_labels: [ __name__ ]
      target_label: __name__
      regex: "(.+):.+_(.+)"
      replacement: "$1:$2"
