---
host: 0.0.0.0
port: 8080
vm_import_url: "http://vmagent:8429/api/v1/import/prometheus"
push_interval: 5s
default_labels:
metrics:
- name: test_counter_0
  labels:
    metric_type: counter
    metric_interval: default
  value: 10
  interval: 5s
- name: test_counter_0
  labels:
    metric_type: counter
    metric_interval: default
  value: 15
  interval: 5s
- name: test_counter_1
  labels:
    metric_type: counter
    metric_interval: default
    instance: first
  value: 10
  interval: 5s
- name: test_counter_1
  labels:
    metric_type: counter
    metric_interval: default
    instance: second
  value: 15
  interval: 5s
- name: sporadic_counter
  labels:
    metric_type: counter
    metric_interval: default
    instance: first
    metric_source: lambda
  value: 100
  interval: 65s
- name: sporadic_counter
  labels:
    metric_type: counter
    metric_interval: default
    instance: second
    metric_source: lambda
  value: 100
  interval: 66s
- name: sporadic_counter
  labels:
    metric_type: counter
    metric_interval: default
    instance: first
    metric_source: lambda
  value: 100
  interval: 90s
- name: test_gauge_0
  type: gauge
  labels:
    metric_type: gauge
    metric_interval: default
    instance: first
  random_value:
    min: 10
    max: 20
  interval: 10s
